"2013" = [
    "આબુને રસ્તે બંગલા ચણાય છે",
    "નીચે નમીને",
    "અલી રાસમણી",
    "ડુંગરવાળી ડોશી",
    "બુધ્ધિ આપોને મા બહુચરા રે",
    "રમવા આવોને",
    "હું તો ગઇ’તી મેળે",
    "સાથીયા પુરાવો દ્વારે",
]
