"મંદિર" = [
  "માએ ગરબો કોરાવ્યો",
  "આવો તે રમવા રે",
  "સોનલ ગરબો શિરે",
  "રૂમઝુમ...આવો રણકાર",
  "અંબા અભય પદ દાયિની",
  "ચપટી ભરી ચોખા",
  "અંબાજી હિંચકે ઝુલે રે",
  "સામા ડુંગરેથી ઉતર્યો વાધ રે",
  "વાદલડી વરસી રે",
  "વા વાયા ને વાદળ ઊમટ્યાં",
  "તમે એક વાર મારવાડ",
  "કુમકુમના પગલાં પડ્યાં",
  "માડી તારા મંદિરીયામાં",
  "મંગળ વરસે",
  "એક હરતુ ને ફરતુ",
  "હે જગ જનની",
  "કુમકુમ કેરા પગલે",
  "જય જય બહુચર બિરદાળી",
  "ધારા નગરથી",
  "હો ગોરી છમ છમ",
  "બેડાં મેલો ને વાટ",
  "સાચી રે મારી સત રે ભવાની મા",
  "રમે અંબે મા ચાચરના ચોકમાં",
  "રઘુપતિ રાઘવ",
  "ખેલ ખેલ રે ભવાની મા"
]

[Kids]
"બે તાળી" = [
  "માએ ગરબો કોરાવ્યો",
  "આવો તે રમવા રે",
  "સોનલ ગરબો શિરે",
  "दुःख भरे दिन बीते",
  "રૂમઝુમ...આવો રણકાર",
  "અંબાજી હિંચકે ઝુલે રે",
  "भोली सूरत दिल के खोटे",
  "બિરદાળી બહુચરવાળી શંખલપુરવાળી",
  "બેડલે પાણી",
  "કુમકુમના પગલાં પડ્યાં",
  "વૃંદાવનમાં થનકાર"
]
"ત્રણ તાળી" = [
  "એક હરતુ ને ફરતુ",
  "मनवा लागे",
  "मैं तुलसी तेरे आँगन की",
  "કુમકુમ કેરા પગલે",
  "दीवानी मस्तानी",
  "હો ગોરી છમ છમ",
  "ताल से ताल",
  "હે જગ જનની",
  "तुम पास आये",
  "जग घूमेया",
  "સાચી રે મારી સત રે ભવાની મા",
  "બેડાં મેલો ને વાટ",
  "जादूगर सैंया",
  "જય જય બહુચર બિરદાળી",
  "રઘુપતિ રાઘવ"
]
"રાસ" = [
  "હે મા અંબા જગદંબા",
  "અમે મહિયારાં રે",
  "નટવર નાનો રે",
  "કહો પૂનમનાં ચાંદ ને",
  "આભમાં ઉગ્યો છે",
  "વેણુ વગાડતો",
  "आधा हे चंद्रमा",
  "श्याम तेरी बंसी",
  "કૃષ્ણ ભગવાન ચાલ્યા",
  "કુકડા તારી બોલી",
  "हँसता हुआ नूरानी चेहरा",
  "કસુંબીનો રંગ",
  "तु गंगाकी मोज",
  "ઢોલીડા ઢોલ ધીમો",
  "નગાડા સંગ ઢોલ બાજે",
  "गोविंदा आला रे",
  "कुडी पंजाबन",
  "दिल ले गयी कूदी गुजरात की",
  "दमा दम मस्त कलंदर"
]
