"૨૦૧૭-૦૯-૨૫" = [
  "થનકારો થનકારો",
  "રૂમઝુમ...આવો રણકાર",
  "ઝીણી ઝીણી",
  "સોનલ ગરબો શિરે",
  "માએ ગરબો કોરાવ્યો",
  "આવો તે રમવા રે",
  "બિરદાળી બહુચરવાળી શંખલપુરવાળી",
  "અલી રાસમણી",
  "મા તારો ગરબો ઝાકમજોળ",
  "ઝુલે ઝુલે ગબ્બરની માય",
  "હાં રે મા આરાસુરથી આવ્યા",
  "પાટણી પટોળા પહેર્યા",
  "ચપટી ભરી ચોખા",
  "હે લેજો તાળી ને દેજો",
  "ઇંધણા વીણવા",
  "ગોવિંદા આલા રે",
  "અંબા કહે બહુચર ચાલો સંતાકુકડી",
  "ઝનન ઝનન ઝાંજરીયુ જળકે છે"
]
"આઠમ" = [
  "હે માને આજે હું શ્રીફળ ચડાવું",
  "એક હરતુ ને ફરતુ",
  "બજે તાલ મંજીરા ઢોલ",
  "ઊંચા ઊંચા રે મારી માડીનાં",
  "મે તો શણગાર્યો ચાચર ચોક",
  "बनवारी रे",
  "ધારા નગરથી",
  "एक दिन वो भोले भंडारी",
  "રૂમઝુમ કરતા આવો",
  "લાલ રે ગુલાબનાં ફુલોની ચુંદડી",
  "જય જય બહુચર બિરદાળી",
  "સાચી રે મારી સત રે ભવાની મા"
]

[Kids]
"ગરબા" = [
  "એક હરતુ ને ફરતુ",
  "હે જગ જનની",
  "मनवा लागे",
  "झनक झनक तोरी बाजे पायलिया",
  "રૂમઝુમ કરતા આવો",
  "હે માને આજે હું શ્રીફળ ચડાવું",
  "जग घूमेया",
  "મે તો શણગાર્યો ચાચર ચોક",
  "પધારો સોનલ ગરબો",
  "ઊંચા ઊંચા રે મારી માડીનાં",
  "इन्हीं लोगों ने",
  "કુમકુમ કેરા પગલે",
  "मस्त मस्त दो नैन",
  "ताल से ताल",
  "તારી આંખનો અફીણી",
  "दीवानी मस्तानी",
  "તાલીઓનાં તાલે",
  "ઊંચી તલાવડીની કોર પાણી ગ્યા'તાં",
  "સાચી રે મારી સત રે ભવાની મા",
  "जादूगर सैंया",
  "मेरा पिया घर आया, ओ रामजी",
  "दमा दम मस्त कलंदर"
]
"રાસ" = [
  "વેણુ વગાડતો",
  "અમે મહિયારાં રે",
  "નટવર નાનો રે",
  "તારા નામની ચુંદડી ઓઢી",
  "जीत ही लेंगे बाजी हम तुम",
  "આભમાં ઉગ્યો છે",
  "साँसों की ज़रूरत है",
  "મહેંદી તે વાવી",
  "देखा है पहली बार",
  "आधा हे चंद्रमा",
  "કુંજ બિહારી પિતાંબરધારી",
  "કૃષ્ણ ભગવાન ચાલ્યા",
  "आये हो मेरी जिन्दगी में",
  "કસુંબીનો રંગ",
  "अगर तुम हो",
  "तु गंगाकी मोज",
  "डम डम डिगा डिगा",
  "વા વાયા ને વાદળ ઊમટ્યાં",
  "રઘુપતિ રાઘવ",
  "ઢોલીડા ઢોલ ધીમો",
  "કુકડા તારી બોલી - 2",
  "ढोली तारो ढोल बाजे",
  "નગાડા સંગ ઢોલ બાજે",
  "दिल ले गयी कूदी गुजरात की",
  "मेरे देश की धरती",
  "उडें जब जब जुल्फें तेरी",
  "यह देश है वीर जवानों का"
]
