Sunday = [
  "એક હરતુ ને ફરતુ",
  "હે જગ જનની",
  "રૂમઝુમ કરતા આવો",
  "હે માને આજે હું શ્રીફળ ચડાવું",
  "મે તો શણગાર્યો ચાચર ચોક",
  "પધારો સોનલ ગરબો",
  "ઊંચા ઊંચા રે મારી માડીનાં",
  "કુમકુમ કેરા પગલે",
  "હો ગોરી છમ છમ",
  "જય જય બહુચર બિરદાળી",
  "રઘુપતિ રાઘવ",
  "તાલીઓનાં તાલે",
  "સાચી રે મારી સત રે ભવાની મા",
  "એક લાલ દરવાજે",
  "રમે અંબે મા ચાચરના ચોકમાં",
  "રંગતાળી રંગતાળી",
  "નવરાત્રીના નવ નવ દિવસમાં",
  "ખેલ ખેલ રે ભવાની મા",
  "ગોકુળ આવો ગિરધારી"
]
Thursday = [
  "માએ ગરબો કોરાવ્યો",
  "આવો તે રમવા રે",
  "અંબાજી હિંચકે ઝુલે રે",
  "કુમકુમના પગલાં પડ્યાં",
  "સોનલ ગરબો શિરે",
  "રૂમઝુમ...આવો રણકાર",
  "અલી રાસમણી",
  "झीना झीना",
  "બેડલે પાણી",
  "સુના સરવરીયા",
  "મારા તે ચિત્તનો",
  "સામા ડુંગરેથી ઉતર્યો વાધ રે",
  "મેલી દીયોને ગીરધારી",
  "તું કાળી ને કલ્યાણી રે મા",
  "આબુને રસ્તે બંગલા ચણાય છે"
]
"આઠમ" = [
  "માડી તારા વિના",
  "જય જય આરાસુરની રાણી",
  "રૂમઝુમ કરતા આવો",
  "એક હરતુ ને ફરતુ",
  "ગરબે રમવા કેમ ના આવે",
  "પધારો સોનલ ગરબો",
  "રૂમઝુમ ઝાંઝર બોલે ગરબે",
  "જય જય બહુચર બિરદાળી",
  "કુમકુમ કેરા પગલે",
  "બેડાં મેલો ને વાટ",
  "બજે તાલ મંજીરા ઢોલ",
  "હો ગોરી છમ છમ",
  "બેડલે બંધાયો",
  "સાચી રે મારી સત રે ભવાની મા",
  "ઘર ઘર દિવડાં પ્રગટાવો"
]

[CPCC]
"૨ તાળી" = [
  "હે મા અંબા જગદંબા",
  "રૂમઝુમ...આવો રણકાર",
  "ઝીણી ઝીણી",
  "ઝુલે ઝુલે ગબ્બરની માય",
  "झीना झीना",
  "આવો તે રમવા રે",
  "અંબાજી હિંચકે ઝુલે રે",
  "બિરદાળી બહુચરવાળી શંખલપુરવાળી",
  "અલી રાસમણી.1",
  "મંગળ દિવડાની મંગળ જ્યોતિ",
  "થનકારો થનકારો",
  "હાં રે મા આરાસુરથી આવ્યા",
  "સોનલ ગરબો શિરે",
  "दुःख भरे दिन बीते",
  "માએ ગરબો કોરાવ્યો",
  "साँसों की ज़रूरत है",
  "સુના સરવરીયા",
  "હે આવી આસોની રઢિયાળી",
  "માડી તારા મંદિરીયામાં",
  "ઇંધણા વીણવા",
  "તરણે તરણે રે મેળે ગ્યા 'તા",
  "હે લેજો તાળી ને દેજો",
  "રૂમઝુમ કરતા માડી આવે",
  "રંગતાળી રંગતાળી",
  "ઢોલીડા ઢોલ ધીમો",
  "તું કાળી ને કલ્યાણી રે મા",
  "ઝાંઝરીયું ઝમકે છે",
  "અંબા કહે બહુચર ચાલો સંતાકુકડી",
  "સૈયર વનરા તે વનમાં વેણું વાગી"
]
"૩ તાળી" = [
  "एकदंताय वक्रतुण्डाय",
  "પધારો સોનલ ગરબો",
  "હે માને આજે હું શ્રીફળ ચડાવું",
  "જય જય આરાસુરની રાણી",
  "तुमको पिया दिल दिया",
  "मार दिया जाए की छोड़ दिया जाए",
  "હે જગ જનની",
  "મે તો શણગાર્યો ચાચર ચોક",
  "बनवारी रे",
  "दीवानी मस्तानी",
  "લાલ રે ગુલાબનાં ફુલોની ચુંદડી",
  "सिलसिला ये चाहत का",
  "હો ગોરી છમ છમ",
  "सैंया दिल में आना रे",
  "બેડલે બંધાયો",
  "મુને એકલી જાણીને",
  "तुम पास आये",
  "તારી આંખનો અફીણી",
  "तुझे देखा तो ये जाना सनम",
  "બેડાં મેલો ને વાટ",
  "ઊંચા ઊંચા રે મારી માડીનાં",
  "मस्त मस्त दो नैन",
  "તાલીઓનાં તાલે",
  "બજે તાલ મંજીરા ઢોલ",
  "चल छैय्याँ छैय्याँ",
  "ધારા નગરથી",
  "ताल से ताल",
  "સાચી રે મારી સત રે ભવાની મા",
  "परदेसी परदेसी जाना नहीं",
  "રમે અંબે મા ચાચરના ચોકમાં",
  "ચોખલિયાળી ચુંદડી",
  "घनन घनन",
  "એક લાલ દરવાજે",
  "ફાગણ ફોરમ તો આયો"
]
"રાસ" = [
  "ગોરી રાધા ને કાળો કાન",
  "તારા વિના વેરણ",
  "તારા નામની ચુંદડી ઓઢી",
  "जीत ही लेंगे बाजी हम तुम",
  "કસુંબીનો રંગ",
  "तु गंगाकी मोज",
  "श्याम तेरी बंसी",
  "મહેંદી તે વાવી",
  "મોરલીયો, મધુવનમાં બોલ્યો",
  "આભમાં ઉગ્યો છે",
  "કૃષ્ણ ભગવાન ચાલ્યા",
  "કુંજ બિહારી પિતાંબરધારી",
  "મુને ગમતો કાનુડો રૂપાળો",
  "મારા તે ચિત્તનો",
  "વા વાયા ને વાદળ ઊમટ્યાં",
  "હે તને જાતાં જોઇ",
  "પંખીડા તું ઉડી જાજે પાવાગઢ",
  "हिलोरी",
  "भोली सूरत दिल के खोटे",
  "हँसता हुआ नूरानी चेहरा",
  "વાદલડી વરસી રે",
  "ઓલો કાળિયો રે",
  "हम भी हे तुम भी हो",
  "ढोली तारो ढोल बाजे",
  "નગાડા સંગ ઢોલ બાજે",
  "ઓઢણી ઓઢું ને ઉડી જાય",
  "देवा श्री गणेशा",
  "વાંકી વળુ તો",
  "એક સાબરકાંઠા",
  "गोविंदा आला रे",
  "એક વાર બોલું",
  "મોતી વેરાણાં ચોકમાં",
  "जादूगर सैंया",
  "एक दो तीन",
  "भूमरो भूमरो"
]

[Kids]
"ગરબા" = [
  "મોગલ આવે",
  "એક હરતુ ને ફરતુ",
  "હે જગ જનની",
  "मनवा लागे",
  "झनक झनक तोरी बाजे पायलिया",
  "રૂમઝુમ કરતા આવો",
  "હે માને આજે હું શ્રીફળ ચડાવું",
  "जग घूमेया",
  "મે તો શણગાર્યો ચાચર ચોક",
  "પધારો સોનલ ગરબો",
  "ઊંચા ઊંચા રે મારી માડીનાં",
  "इन्हीं लोगों ने",
  "કુમકુમ કેરા પગલે",
  "मस्त मस्त दो नैन",
  "ताल से ताल",
  "તારી આંખનો અફીણી",
  "दीवानी मस्तानी",
  "તાલીઓનાં તાલે",
  "ઊંચી તલાવડીની કોર પાણી ગ્યા'તાં",
  "સાચી રે મારી સત રે ભવાની મા",
  "घूमर",
  "सजदा",
  "जादूगर सैंया",
  "मेरा पिया घर आया, ओ रामजी",
  "दमा दम मस्त कलंदर"
]
"રાસ" = [
  "અમે મહિયારાં રે",
  "નટવર નાનો રે",
  "વેણુ વગાડતો",
  "તારા નામની ચુંદડી ઓઢી",
  "जीत ही लेंगे बाजी हम तुम",
  "આભમાં ઉગ્યો છે",
  "साँसों की ज़रूरत है",
  "મહેંદી તે વાવી",
  "તારા વિના શ્યામ",
  "आधा हे चंद्रमा",
  "કુંજ બિહારી પિતાંબરધારી",
  "કૃષ્ણ ભગવાન ચાલ્યા",
  "आये हो मेरी जिन्दगी में",
  "કસુંબીનો રંગ",
  "तु गंगाकी मोज",
  "કોણ હલાવે લીંબડી",
  "વા વાયા ને વાદળ ઊમટ્યાં",
  "परी हूं मैं",
  "ઇંધણા વીણવા",
  "जवानी जान-ए-मन",
  "करिये ना करिये ना",
  "तूने मारी एंट्रियां",
  "હો આવી ગઈ રાત",
  "कुडी पंजाबन",
  "से शावा शावा",
  "यह देश है वीर जवानों का"
]
