Wednesday = [
  "માતાજીના ઊંચા મંદિર નીચા મોલ",
  "ઝુલે ઝુલે ગબ્બરની માય",
  "મા પાવા તે ગઢથી ઉતર્યા",
  "झीना झीना",
  "સામા ડુંગરેથી ઉતર્યો વાધ રે",
  "તમે એક વાર મારવાડ",
  "અંબાજી હિંચકે ઝુલે રે",
  "અંબા અભય પદ દાયિની",
  "સોનલ ગરબો શિરે",
  "ચપટી રે ચોખા ને ચપટી રે કંકુ",
  "ઊંચા ઊંચા રે માડી તારાં ડુંગરા",
  "સવા મણ સોનુ",
  "વા વાયા ને વાદળ ઊમટ્યાં",
  "એક વણઝારી ઝૂલણાં",
  "આબુને રસ્તે બંગલા ચણાય છે",
  "નવરાત્રીના નવ નવ દિવસમાં"
]
Thursday = [
  "એક હરતુ ને ફરતુ",
  "કુમકુમ પગલે રે",
  "રૂમઝુમ કરતા આવો",
  "કુમકુમ કેરા પગલે",
  "જય જય બહુચર બિરદાળી",
  "આરાસુરમાં અંબા કરે રે કિલ્લોલ",
  "સાથીયા પુરાવો દ્વારે",
  "જય જય બોલો આનંદે અંબે માતની",
  "માનો ગરબો રે",
  "રઘુપતિ રાઘવ",
  "તાલીઓનાં તાલે",
  "ચોખલિયાળી ચુંદડી",
  "સાચી રે મારી સત રે ભવાની મા",
  "ખેલ ખેલ રે ભવાની મા",
  "રમે અંબે મા ચાચરના ચોકમાં"
]

[Kids]
"ગરબા" = [
  "એક હરતુ ને ફરતુ",
  "मनवा लागे",
  "હે જગ જનની",
  "तू कितनी अच्छी है",
  "રૂમઝુમ કરતા આવો",
  "जग घूमेया",
  "સરોવર ઝીલવા ને ગઈ 'તી",
  "તારી આંખનો અફીણી",
  "दीवानी मस्तानी",
  "वो किसना है",
  "मीठे रस से भरी रे",
  "छोटी छोटी गैया",
  "મારા ઘટમાં બિરાજતા",
  "अई अई या सूकू सूकू",
  "Twinkle Twinkle",
  "રઘુપતિ રાઘવ",
  "ABCD",
  "वंदे मातरम"
]
"રાસ" = [
  "વેણુ વગાડતો",
  "અમે મહિયારાં રે",
  "નટવર નાનો રે",
  "આભમાં ઉગ્યો છે",
  "આજે પ્રિતમને પ્રીત મળી જાશે",
  "તારા નામની ચુંદડી ઓઢી",
  "झीना झीना",
  "મહેંદી તે વાવી",
  "आधा हे चंद्रमा",
  "કૃષ્ણ ભગવાન ચાલ્યા",
  "साँसों की ज़रूरत है",
  "કોણ હલાવે લીંબડી",
  "करिये ना करिये ना"
]
